MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = font-win.prf \
       font-mac.prf \
       font-x11.prf \
       font-gcu.prf \
       font-sdl.prf \
       font-xxx.prf \
       message.prf \
       pref.prf \
       font.prf \
       user.prf \
       graf.prf \
       flvr-new.prf graf-new.prf xtra-new.prf \
       flvr-xxx.prf graf-xxx.prf xtra-xxx.prf \
       flvr-dvg.prf graf-dvg.prf xtra-dvg.prf \
       flvr-nmd.prf graf-nmd.prf xtra-nmd.prf \
       flvr-shk.prf graf-shk.prf xtra-shk.prf

PACKAGE = pref
